dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
  - "nightly"
env:
  - PACKAGE=fluent.syntax
  - PACKAGE=fluent.runtime
install: pip install tox-travis
script: cd $PACKAGE; tox
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l20n"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "#%{build_number} %{message} %{build_url}"
      - "Change by %{author}: %{compare_url}"
