sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
install: pip install tox-travis
script: tox
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l20n"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "#%{build_number} %{message} %{build_url}"
      - "Change by %{author}: %{compare_url}"
