#!/usr/bin/env python3

import argparse

from fluent.docs import build, pre_pub


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'repo_name',
        help='URL prefix on the web. Repo name on gh-pages'
    )
    parser.add_argument(
        '--to-publish', dest='pre_pub', action='store_true',
        help='Use this to publish to Github. Builds faster without.'
    )
    default_docs = ['.', 'fluent.syntax', 'fluent.pygments', 'fluent.runtime']
    parser.add_argument(
        '--doc', action='append', choices=default_docs,
        help='Only build select documentation roots.'
    )
    args = parser.parse_args()
    if args.doc is None:
        args.doc = default_docs
    build(args.repo_name, args.doc)
    if args.pre_pub:
        pre_pub(args.repo_name)
