name: integrations

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - .github/workflows/fluent.integration.yml
      - "fluent.syntax/**"
      - "!fluent.syntax/docs/**"
      - "fluent.runtime/**"
      - "!fluent.runtime/docs/**"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/fluent.integration.yml
      - "fluent.syntax/**"
      - "!fluent.syntax/docs/**"
      - "fluent.runtime/**"
      - "!fluent.runtime/docs/**"

jobs:
  integration:
    name: fluent.runtime
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: ./fluent.runtime
        run: |
          python -m pip install wheel
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Install latest fluent.syntax
        working-directory: ./fluent.syntax
        run: |
          python -m pip install .
      - name: Test
        working-directory: ./fluent.runtime
        run: |
          ./runtests.py
